### ISSUE TITLE
[feature-request] Add offset to current episode number

### ISSUE THREAD

**Issue by skj-skj** [glodanif/Pocket_MAL#3]
I am watching aot and wanted to keep track of episodes I have watched and where to continue. I realise that some anime like aot episode numbering doesn't reset after next season.
for example if season 1 ends on 12th episode and season 2 will starts with 13th episode.

but in MAL episode number will always start at 1 so sometimes its not instantaneous to know which episode I left off, I have to do calculate by adding total number of episode in the last season to the current number.

so it will be a cool feature to also show current episode number by an offset value.

**Comment by glodanif** [comment]
Hey, I'm not quite sure what you are asking for.
After completing 25 episodes of AoT S1, do you want the second season to start from the 26th episode in the app, so it's 25-38 instead of 0-12?
If so, I would say there is no easy way to implement something like this, the MAL API doesn't indicate in any shape or form that a title's sequel has some weird numbering and we should start counting from the prequel's last episode and not 0.

**Comment by skj-skj** [comment]
yes MAL api doesn't provide that info and the episode numbering is random in nature some anime do some doesn't, its also depends on the community whether to reset the episode numbering each season or not.

so I would suggest to have an option to give episode offset value. and it will show it like this
ex: if offset value is `25`, so for that season it should display like this `0(25)/12`, `1(26)/12`.

you can give an option to whether use offset feature or not in settings under advance section.

and after long pressing the anime tile in home screen it will show a context menu with options like `set offset`, `remove offset`

once `set offset` is clicked text box will appear with number only input, after entering the offset number. the anime tile should show the episode numbering like this `5(30)/12`.

and when `remove offset` is clicked it will show thr episode number same as before, like this `5/12`.

you can also place the offset episode number somewhere else where it would look pretty in the ui.

**Comment by glodanif** [comment]
I don't think it's something I'm gonna ever implement. It's too much work for a questionable output. I don't mind adding some obscure features that are available if a user wants to opt-in from the settings, but your request doesn't seem to be worth the work and complicating the codebase.
I used to watch a ton of anime and never had a need for something like this.

**Comment by skj-skj** [comment]
no problem, I just thought I would be a cool feature.

**Comment by skj-skj** [comment]
closing the issue, sorry for the trouble.
